routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Main Page
Route::get('/', 'HomeController@index')->name('home');
Auth::routes(['request' => false, 'reset' => false]);

// Inventory Management
Route::resource('/summary', 'Inventory\SummaryController');
Route::get('/summary/filter/{filter}', 'Inventory\SummaryController@filter');
Route::get('/history', 'Inventory\SummaryController@history')->name('inventory');
Route::resource('/list_shelf', 'Inventory\RecheckShelfController');
Route::resource('/list_product', 'Inventory\ProductListController');
Route::get('searchShelf', 'Inventory\RecheckShelfController@searchShelf');
Route::get('searchProduct', 'Inventory\ProductListController@searchProduct');
// Receiving / Put Away
Route::resource('/receiving', 'Items\ReceivingReportController');
Route::resource('/putaway', 'Items\PutAwayController');

// Picking / Packing
Route::resource('/picking', 'Items\PickingReportController');
Route::post('/pick_item', 'Items\PickingReportController@pickItem');
Route::resource('/packing', 'Items\PackingController');

// Administration
Route::resource('/contacts', 'Administration\ContactController');
Route::get('/contacts/filter/{filter}', 'Administration\ContactController@filter');
Route::resource('/products', 'Administration\ProductController');
Route::get('/products/filter/{filter}', 'Administration\ProductController@filter');
Route::resource('/logs', 'Administration\LogController');
Route::post('/report-download', 'Administration\LogController@report');
Route::resource('/roles', 'Administration\RoleController');
Route::get('/roles/filter/{filter}', 'Administration\RoleController@filter');
Route::resource('/users', 'Administration\UserController');
Route::get('/users/filter/{filter}', 'Administration\UserController@filter');
Route::resource('/vendors', 'Administration\VendorController');
Route::get('/vendors/filter/{filter}', 'Administration\VendorController@filter');
Route::post('/uploadproductfile', 'Administration\ProductController@uploadFile');
Route::post('/uploadvendorfile', 'Administration\VendorController@uploadFile');

// Download Route
Route::get('download/{filename}', function ($filename) {
    // Check if file exists in app/storage/file folder
    $file_path = storage_path() .'/file/'. $filename;
    if (file_exists($file_path)) {
        // Send Download
        return Response::download($file_path, $filename, [
            'Content-Length: '. filesize($file_path)
        ]);
    } else {
        // Error
        exit('Requested file does not exist on our server!');
    }
})
->where('filename', '[A-Za-z0-9\-\_\.]+');

app/Http/Controllers/Administration/ContactController.php
<?php

namespace App\Http\Controllers\Administration;

use Illuminate\Http\Request;
use App\Contact;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Contracts\Pagination\Presenter;

use App\Http\Controllers\Controller;

class ContactController extends Controller
{
    /**
    * Get the path the user should be redirected to.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return string
    */
    protected function redirectTo($request)
    {
        return route('login');
    }

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts = Contact::sortable()->paginate(10);
        $filter_value = "";

        return view('administration.contacts.index', compact('contacts', 'filter_value'));
    }

    public function filter($filter)
    {
        $contacts = Contact::where('name', 'LIKE', '%'.$filter.'%')->
     sortable()->
     paginate(10)->
     appends('name', 'LIKE', '%'.$filter.'%');

        $filter_value = $filter;

        return view('administration.contacts.index', compact('contacts', 'filter_value'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!auth()->user()->role->admin) {
            return redirect('/')->with('status', 'Admin Access Required');
        } else {
            return view('administration.contacts.create');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'vendors_id'=>'required',
            'phone_number'=>'required',
            'email'=>'required'
        ]);

        $contact = new Contact([
            'name' => $request->get('name'),
            'vendors_id' => $request->get('vendors_id'),
            'email' => $request->get('email'),
            'job_title' => $request->get('job_title'),
            'city' => $request->get('city'),
            'phone_number' => $request->get('phone_number')
        ]);
        $contact->save();
        return redirect('/contacts')->with('success', 'Contact saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $contacts = Contact::where('vendors_id', '=', $id)->sortable()->paginate(10);
        $filter_value = $contacts->first()->name;

        return view('administration.contacts.index', compact('contacts', 'filter_value'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $contact = Contact::find($id);
        return view('administration.contacts.edit', compact('contact'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'vendors_id'=>'required',
            'phone_number'=>'required',
            'email'=>'required'
        ]);

        $contact = Contact::find($id);
        $contact->name =  $request->get('name');
        $contact->vendors_id = $request->get('vendors_id');
        $contact->email = $request->get('email');
        $contact->job_title = $request->get('job_title');
        $contact->city = $request->get('city');
        $contact->phone_number = $request->get('phone_number');
        $contact->save();

        return redirect('/contacts')->with('success', 'Contact updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contact = Contact::find($id);
        $contact->delete();

        return redirect('/contacts')->with('success', 'contact deleted!!!!');
    }
}

app/Http/Controllers/Administration/LogController.php
<?php

namespace App\Http\Controllers\Administration;

use App\Log;
use PDF;

use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Contracts\Pagination\Presenter;
use Illuminate\Http\Request;

use App\Http\Controllers\Controller;

class LogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected function redirectTo($request)
    {
        return route('login');
    }

    public function __construct()
    {
        $this->middleware('admin');
    }

    public function index(Request $request)
    {
        $logs = Log::sortable()->paginate(10);
        $to = '';
        $from ='';

        return view('administration.log.index', compact('logs', 'to', 'from'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $from = $request->get('from');
        $to = $request->get('to');

        $logs = Log::whereBetween('created_at', [$from, $to])->
        sortable()->
        paginate(10);

        return view('administration.log.index', compact('logs', 'to', 'from'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function report(Request $request)
    {
        $from = $request->get('from-table');
        $to = $request->get('to-table');

        if ($from=='') {
            $data = ['logs'=> Log::all()];
        } else {
            $data = ['logs'=>Log::whereBetween('created_at', [$from, $to])->get()];
        }

        $pdf = PDF::loadView('administration.log.pdf', $data);
        return $pdf->download('logs.pdf');
    }
}

app/Http/Controllers/Administration/ProductController.php
<?php

namespace App\Http\Controllers\Administration;

use App\Product;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Contracts\Pagination\Presenter;

use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    /**
    * Get the path the user should be redirected to.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return string
    */
    protected function redirectTo($request)
    {
        return route('login');
    }

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::sortable()->paginate(10);

        $filter_value = "";

        return view('administration.products.index', compact('products', 'filter_value'));
    }

    public function filter($filter)
    {
        $products = Product::where('product_name', 'LIKE', '%'.$filter.'%')->
      sortable()->
      paginate(10)->
      appends('product_name', 'LIKE', '%'.$filter.'%');

        $filter_value = $filter;

        return view('administration.products.index', compact('products', 'filter_value'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!auth()->user()->role->admin) {
            return redirect('/')->with('status', 'Admin Access Required');
        } else {
            return view('administration.products.create');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
          'product_name'=>'required',
          'vendors_id'=>'required',
          'category'=>'required',
          'price'=>'required',
          'low_threshold' => 'required',
        ]);

        $product = new Product([
          'product_name' => $request->get('product_name'),
          'vendors_id' => $request->get('vendors_id'),
          'category' => $request->get('category'),
          'price' => $request->get('price'),
          'low_threshold' => $request->get('low_threshold')
        ]);
        $product->save();
        return redirect('/products')->with('success', 'Product saved!!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $products = Product::where('id', '=', $id)->
      sortable()->
      paginate(10);

        $filter_value = $products->first()->product_name;

        return view('administration.products.index', compact('products', 'filter_value'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        return view('administration.products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
        'product_name'=>'required',
        'vendors_id'=>'required',
        'category'=>'required',
        'price'=>'required',
      ]);

        $product = Product::find($id);
        $product->product_name = $request->get('product_name');
        $product->vendors_id = $request->get('vendors_id');
        $product->category = $request->get('category');
        $product->price = $request->get('price');
        $product->low_threshold = $request->get('low_threshold');
        $product->save();

        return redirect('/products')->with('success', 'Product updated!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        $product->delete();

        return redirect('/products')->with('success', 'Product deleted!!');
    }
    public function uploadFile(Request $request)
    {
        $request->validate([
        'file'=>'required',
      ]);
        if ($request->input('submit') != null) {
            $file = $request->file('file');
            // File Details
            $filename = $file->getClientOriginalName();
            $extension = $file->getClientOriginalExtension();
            $tempPath = $file->getRealPath();
            $fileSize = $file->getSize();
            $mimeType = $file->getMimeType();

            // Valid File Extensions
            $valid_extension = array("csv");

            // 2MB in Bytes
            $maxFileSize = 2097152;

            // Check file extension
            if (in_array(strtolower($extension), $valid_extension)) {

        // Check file size
                if ($fileSize <= $maxFileSize) {

          // File upload location
                    $location = 'uploads';

                    // Upload file
                    $file->move($location, $filename);

                    // Import CSV to Database
                    $filepath = public_path($location."/".$filename);

                    // Reading file
                    $file = fopen($filepath, 'r');

                    $importData_arr = array();
                    $i = 0;

                    while (($filedata = fgetcsv($file, 1000, ",")) !== false) {
                        $num = count($filedata);

                        // Skip first row (Remove below comment if you want to skip the first row)
                        if ($i == 0) {
                            $i++;
                            continue;
                        }
                        for ($c=0; $c < $num; $c++) {
                            $importData_arr[$i][] = $filedata [$c];
                        }
                        $i++;
                    }
                    fclose($file);
                    unlink($filepath);
                    $ignore_count = 0;
                    // Insert to MySQL database
                    foreach ($importData_arr as $importData) {
                        $insertData = array(
               "product_name"=>$importData[0],
               "vendors_id"=>$importData[1],
               "category"=>$importData[2],
               "price"=>$importData[3],
               "low_threshold"=>$importData[4]);
                        if (Product::insertData($insertData) > 0) {
                            $ignore_count += 1;
                        }
                    }

                    if ($ignore_count > 0) {
                        $message = 'Import Successful.'.PHP_EOL.'Ignored Lines '. $ignore_count;
                    } else {
                        $message = 'Import Successful.';
                    }
                } else {
                    $message = 'File too large. File must be less than 2MB.';
                }
            } else {
                $message = 'Invalid File Extension.';
            }
        }

        // Redirect to index
        return redirect()->action('Administration\ProductController@index')->with('success', $message);
    }
}

resources/views/administration/roles/create.blade.php
@extends('navbar')

@section('context')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add Roles list</h1>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('roles.store') }}">
          @csrf
          <div class="form-group">
              <label for="role_name">Name:</label>
              <input type="text" class="form-control" name="role_name"/>
          </div>

          <div class="form-group">
              <label for="admin">Admin:</label>
              <input type="radio" class="option-input radio" name="admin" id="1" value="1">&emsp; Authorize &nbsp;&nbsp;&nbsp;&nbsp;
              <input type="radio" class="option-input radio" name="admin" id="0" value="0">&emsp; Restrict
          </div>
<br><br>
          <div class="form-group">
              <label for="moderator">Moderator:</label>
              <input type="radio" class="option-input radio" name="moderator" id="1" value="1">&emsp; Authorize &nbsp;&nbsp;&nbsp;&nbsp;
              <input type="radio" class="option-input radio" name="moderator" id="0" value="0">&emsp; Restrict
          </div>
<br><br>
          <div class="form-group">
              <label for="receiving">Receiving:</label>
              <input type="radio" class="option-input radio" name="receiving" id="1" value="1">&emsp; Authorize &nbsp;&nbsp;&nbsp;&nbsp;
              <input type="radio" class="option-input radio" name="receiving" id="0" value="0">&emsp; Restrict
          </div>
<br><br>
          <div class="form-group">
              <label for="inventory">Inventory:</label>
              <input type="radio" class="option-input radio" name="inventory" id="1" value="1">&emsp; Authorize &nbsp;&nbsp;&nbsp;&nbsp;
              <input type="radio" class="option-input radio" name="inventory" id="0" value="0">&emsp; Restrict
          </div>
<br><br>
          <div class="form-group">
              <label for="putting_away">Putting Away:</label>
              <input type="radio" class="option-input radio" name="putting_away" id="1" value="1">&emsp; Authorize &nbsp;&nbsp;&nbsp;&nbsp;
              <input type="radio" class="option-input radio" name="putting_away" id="0" value="0">&emsp; Restrict
          </div>
<br><br>
<div class="form-group row mb-0">
    <div class="col-md-6 offset-md-4">
          <button type="submit" class="btn btn-primary">Add Item</button>
        </div>
      </div>
      </form>
  </div>
</div>

@endsection

resources/views/administration/roles/edit.blade.php
@extends('navbar') @section('context')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update role list</h1> @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> @endif
        <form method="post" action="{{ route('roles.update', $role->id) }}">
            @method('PATCH') @csrf
            <div class="form-group">

                <label for="role_name">Name:</label>
                <input type="text" class="form-control" name="role_name" value="{{ $role->role_name }}" />
            </div>

            <div class="form-group">
                <label for="admin">Admin:</label>
                <input type="radio" class="option-input radio" name="admin" value="1" id="1" />&emsp; Authorize &nbsp;&nbsp;&nbsp;&nbsp;
                <input type="radio" class="option-input radio" name="admin" value="0" id="0" />&emsp; Restrict
            </div>

            <div class="form-group">
                <label for="moderator">Moderator:</label>
                <input type="radio" class="option-input radio" name="moderator" value="1" id="1" />&emsp;Authorize &nbsp;&nbsp;&nbsp;&nbsp;
                <input type="radio" class="option-input radio" name="moderator" value="0" id="0" />&emsp;Restrict
            </div>

            <div class="form-group">
                <label for="receiving">Receiving:</label>
                <input type="radio" class="option-input radio" name="receiving" value="1" id="1" />&emsp;Authorize &nbsp;&nbsp;&nbsp;&nbsp;
                <input type="radio" class="option-input radio" name="receiving" value="0" id="0" />&emsp;Restrict
            </div>

            <div class="form-group">
                <label for="inventory">Inventory:</label>
                <input type="radio" class="option-input radio" name="inventory" value="1" id="1" />&emsp;Authorize &nbsp;&nbsp;&nbsp;&nbsp;
                <input type="radio" class="option-input radio" name="inventory" value="0" id="0" />&emsp;Restrict
            </div>

            <div class="form-group">
                <label for="putting_away">Putting Away:</label>
                <input type="radio" class="option-input radio" name="putting_away" value="1" id="1" />&emsp;Authorize &nbsp;&nbsp;&nbsp;&nbsp;
                <input type="radio" class="option-input radio" name="putting_away" value="0" id="0" />&emsp;Restrict
            </div>

            <button type="submit" class="btn btn-primary">Update</button>
            <button type="reset" value="reset">Clear Item</button>
        </form>
    </div>
</div>
@endsection

resources/views/administration/roles/index.blade.php
@extends('navbar') @section('context')
<div class="col-sm-12">

    @if(session()->get('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}
    </div>
    @endif
</div>
<div class="row">
  <div class="col-sm-12">
        <h1 class="display-3"><img class="page-logo" src="/images/icons/roles.png"/>Roles Management</h1>
        <div>
            <a style="margin: 19px;" href="{{ route('roles.create')}}" class="btn btn-primary">Register New Role</a>
        </div>
        <div class="form-group row">
            <div class="col-md-8">
                <label for="search" class="col-md-3 col-form-label text-md-right">Search roles</label>
                <input id="search" autocomplete="off" type="text" class="typeahead form-control" name="search_value" value="{{ $filter_value }}">
                <script>
                    $('.typeahead').on('keydown', function(e) {
                        if (e.keyCode == 13) {
                            var search_text = document.getElementById("search").value;
                            window.location.replace("/roles/filter/".concat(search_text));
                        }
                    });
                </script>
            </div>
        </div>
        <div style="overflow-x:auto;">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>@sortablelink('role_name', 'Role Name')</th>
                        <th>@sortablelink('admin', 'Admin')</th>
                        <th>@sortablelink('moderator', 'Moderator')</th>
                        <th>@sortablelink('receiving', 'Receiving')</th>
                        <th>@sortablelink('inventory', 'Inventory')</th>
                        <th>@sortablelink('putting_away', 'Putting Away')</th>
                        <th colspan=2>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($roles as $role)
                    <tr>
                        <td>{{$role->role_name}}</td>
                        <td>@if($role->admin == 1) Authorized @else Restricted @endif
                        </td>
                        <td>@if($role->moderator == 1) Authorized @else Restricted @endif
                        </td>
                        <td>@if($role->receiving == 1) Authorized @else Restricted @endif
                        </td>
                        <td>@if($role->inventory == 1) Authorized @else Restricted @endif
                        </td>
                        <td>@if($role->putting_away == 1) Authorized @else Restricted @endif
                        </td>
                        <td>
                            <a href="{{ route('roles.edit',$role->id)}}" class="btn btn-primary">Edit</a>
                        </td>
                        <td>
                            <form class="delete" action="{{ route('roles.destroy', $role->id)}}" method="post">
                                @csrf @method('DELETE')
                                <input type="submit" class="btn btn-danger" value="Delete">
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        {!! $roles->appends(\Request::except('page'))->render() !!}
    </div>
</div>

<script>
    $(".delete").on("submit", function(){
        return confirm("Are you sure?");
    });
</script>

@endsection