routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Main Page
Route::get('/', 'HomeController@index')->name('home');
Auth::routes(['request' => false, 'reset' => false]);

// Inventory Management
Route::resource('/summary', 'Inventory\SummaryController');
Route::get('/summary/filter/{filter}', 'Inventory\SummaryController@filter');
Route::get('/history', 'Inventory\SummaryController@history')->name('inventory');
Route::resource('/list_shelf', 'Inventory\RecheckShelfController');
Route::resource('/list_product', 'Inventory\ProductListController');
Route::get('searchShelf', 'Inventory\RecheckShelfController@searchShelf');
Route::get('searchProduct', 'Inventory\ProductListController@searchProduct');
// Receiving / Put Away
Route::resource('/receiving', 'Items\ReceivingReportController');
Route::resource('/putaway', 'Items\PutAwayController');

// Picking / Packing
Route::resource('/picking', 'Items\PickingReportController');
Route::post('/pick_item', 'Items\PickingReportController@pickItem');
Route::resource('/packing', 'Items\PackingController');

// Administration
Route::resource('/contacts', 'Administration\ContactController');
Route::get('/contacts/filter/{filter}', 'Administration\ContactController@filter');
Route::resource('/products', 'Administration\ProductController');
Route::get('/products/filter/{filter}', 'Administration\ProductController@filter');
Route::resource('/logs', 'Administration\LogController');
Route::post('/report-download', 'Administration\LogController@report');
Route::resource('/roles', 'Administration\RoleController');
Route::get('/roles/filter/{filter}', 'Administration\RoleController@filter');
Route::resource('/users', 'Administration\UserController');
Route::get('/users/filter/{filter}', 'Administration\UserController@filter');
Route::resource('/vendors', 'Administration\VendorController');
Route::get('/vendors/filter/{filter}', 'Administration\VendorController@filter');
Route::post('/uploadproductfile', 'Administration\ProductController@uploadFile');
Route::post('/uploadvendorfile', 'Administration\VendorController@uploadFile');

// Download Route
Route::get('download/{filename}', function ($filename) {
    // Check if file exists in app/storage/file folder
    $file_path = storage_path() .'/file/'. $filename;
    if (file_exists($file_path)) {
        // Send Download
        return Response::download($file_path, $filename, [
            'Content-Length: '. filesize($file_path)
        ]);
    } else {
        // Error
        exit('Requested file does not exist on our server!');
    }
})
->where('filename', '[A-Za-z0-9\-\_\.]+');

resources/views/item_out/picking/create.blade.php
@extends('navbar') @section('context')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="display">
                <div class="display-header"></div>
                <div>
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    <br /> @endif
                    <div class="card-body">

                        <form method="post" action="{{ route('picking.store') }}">
                            @csrf
                            <div class="form-group">
                                <h3 class="display-6"> Create Picking Report </h3>
                            </div>
                            <br/>
                            <div class="form-group row">
                                <label for="createdBy" class="col-md-3 col-form-label text-md-right"> Created By </label>
                                <div class="col-md-8">
                                    <label>{{ auth()->user()->name }}</label>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-3 col-form-label text-md-right">Report Name</label>
                                <div class="col-md-8">
                                    <input id="report_name" type="text" name="name" />
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="date" class="col-md-3 col-form-label text-md-right"> Report date </label>
                                <div class="col-md-8">
                                    <input id="date" type="date" name="date" />
                                </div>
                            </div>

                            <br />
                            <br />

                            <table style="width:70%">
                                <div class="form-group row">
                                    <thead>
                                        <tr>
                                            <th> Product Name </th>
                                            <th> Quantity </th>
                                        </tr>
                                    </thead>
                                </div>
                                <tbody id="picking">
                                    <tr id='row1'>
                                        <td>
                                            <div class="form-group autocomplete">
                                                <input class="search" autocomplete="off" type="text" name="product[1][id]" placeholder="Product">
                                            </div>
                                        </td>
                                        <td>
                                            <div class="form-group" name="quantity">
                                                <input type="number" name="product[1][quantity]" placeholder="10"/>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <br/>
                            <br/>
                            <p> <a href="javascript:;" id="add-product" class="btn btn-primary">Add Product</a> </p>

                            <p>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </p>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    let i = 2;
    document.getElementById('add-product').onclick = function() {
        let template = `
        <tr>
        <td>
            <div class= "autocomplete">
               <input class="search" autocomplete="off" type="text" name="product[${i}][id]" placeholder="Product">
            </div>
        </td>
        <td>
            <div class="form-group" name="quantity">
                <input type="number" name="product[${i}][quantity]" placeholder="10"/>
            </div>
        </td>
    </tr>
    <td>
        <div class="form-group">
            <button class="buang btn-danger" onclick="buang(${i})" id="delete" name="delete[${i}][item]"> X </button>
        </div>
    </td>
    `;

        let container = document.getElementById('picking');
        let div = document.createElement('tr');
        div.setAttribute('id', `row${i}`);
        div.innerHTML = template;
        container.appendChild(div);

        i++;

        $('.search').trigger('added');
    }

    function buang(rowNumber) {
        document.getElementById(`row` + rowNumber).remove();
    }
</script>
<script type="text/javascript">
        var path = "{{ url('searchProduct') }}";
        var typeaheadSettings = {
            minLength: 0,
            source: function(query, process) {
                return $.get(path, {
                    query: query
                }, function(data) {
                    return process(data);
                });
            }
        }
        $('.search').typeahead(typeaheadSettings);

        $('.search').on('added', function(){
            $('.search').typeahead(typeaheadSettings);
        });
    </script>
@endsection

resources/views/item_out/picking/index.blade.php
@extends('navbar') @section('context')
<div class="col-sm-12">

    @if(session()->get('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}
    </div>
    @endif
</div>
<div class="row">
    <div class="col-sm-12">
        <h1 class="display-3"><img src="/images/icons/picking.png" class="page-logo" />Picking Report</h1>
        <div>
            <a style="margin: 19px;" href="{{ route('picking.create')}}" class="btn btn-primary">New Report</a>
        </div>
        <div style="overflow-x:auto;">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>@sortablelink('report_name', 'Report Name')</th>
                        <th>@sortablelink('user.name', 'Generated By')</th>
                        <th>@sortablelink('execution_date', 'Execution Date')</th>
                        <th colspan="2"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($reports as $report)
                    <tr>
                        <td>{{$report->report_name}}</td>
                        <td><a href="/users/{{$report->user->id}}">{{$report->user->name}}</a></td>
                        <td>{{$report->execution_date}}</td>
                        <td>
                            <a href="{{ route('picking.show', $report->id) }}" class="btn btn-primary">Items</a>
                        </td>
                        <td>
                            <form class="delete" action="{{ route('picking.destroy', $report->id) }}" method="post">
                                @csrf @method('DELETE')
                                <input type="submit" class="btn btn-danger" value="Delete">
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        {!! $reports->appends(\Request::except('page'))->render() !!}
    </div>
</div>

<script>
    $(".delete").on("submit", function(){
        return confirm("Are you sure?");
    });
</script>
@endsection

resources/views/item_out/picking/items.blade.php
@extends('navbar')

@section('context')
<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div>
  @endif
</div>
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Picking: {{$report_items[0]->report->report_name}}</h1>
    <div>
      <a style="margin: 19px;" href="{{ route('picking.index')}}" class="btn btn-primary">Back to Report List</a>
    </div>
  <table class="table table-striped">
    <thead>
        <tr>
          <th>@sortablelink('product.product_name', 'Name')</th>
          <th>@sortablelink('quantity', 'Quantity')</th>
          <th>@sortablelink('status.status_name', 'Status')</th>
          <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach($report_items as $item)
        <tr>
            <td><a href="/products/{{$item->product->id}}">{{$item->product->product_name}}</a></td>
            <td>{{$item->quantity}}</td>
            <td>{{$item->status->status_name}}</td>
            <td>
              @if ($item->statuses_id == 5)
                <a href="{{ route('picking.edit', $item->id)}}" class="btn btn-primary">Pickup Item</a>
              @endif
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
</div>
</div>
@endsection

resources/views/item_out/picking/selectshelf.blade.php
@extends('navbar') @section('context') @if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
<br /> @endif
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="display">
                <div class="display-header">Item to pick up : {{$item->product->product_name}}</div>
                <br/>
                <div class="display-body">
                    <form method="post" action="/pick_item">
                        @method('POST') @csrf
                        <div class="form-group row">
                            <label for="shelf_number" class="col-md-4 col-form-label text-md-right">Shelf</label>
                          </div>
                          <div class="form-group row">
                              <label for="number-of-item" class="col-md-3 col-form-label text-md-right">Item Quantity</label>
                              <div class="col-md 8">
                                <input id="number-of-item" type="number" min="1" max="{{ $item_left }}" class="form-control{{ $errors->has('number-of-item') ? ' is-invalid' : '' }}" name="number-of-item" value="{{ $item_left }}" required autofocus> @if ($errors->has('number-of-item'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('number-of-item') }}</strong>
                                </span> @endif
                            </div>
                          </div>

                          <div class="form-group row">
                              <label for="select_shelf" class="col-md-3 col-form-label text-md-right">Shelf Number</label>
                              <div class="col-md 8">
                                <input id="select_shelf" type="text" class="form-control{{ $errors->has('select_shelf') ? ' is-invalid' : '' }}" name="select_shelf" value="{{ old('select_shelf') }}" required autofocus> @if ($errors->has('select_shelf'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('select_shelf') }}</strong>
                                </span> @endif
                            </div>
                          </div>

                        </div>
                        <input id="item" type="hidden" name="item" value="{{ $item->id }}">
                        <input id="item-left" type="hidden" name="item-left" value="{{ $item_left }}"> @foreach($add_shelf as $list_shelf)
                        <input id="add-list" type="hidden" name="shelf-list[]" value="{{ $list_shelf }}"> @endforeach @foreach($add_quantity as $list_quantity)
                        <input id="add-list" type="hidden" name="quantity-list[]" value="{{ $list_quantity }}"> @endforeach
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Pick from Inventory
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection